require "bundler"
Bundler::GemHelper.install_tasks

require "rake/testtask"
require "rake/extensiontask"

Rake::ExtensionTask.new "arrow_file_write" do |ext|
  ext.lib_dir = "lib/fluent/plugin"
end

Rake::TestTask.new(:test) do |t|
  t.libs.push("lib", "test")
  t.test_files = FileList["test/**/test_*.rb"]
  t.verbose = true
  t.warning = true
end

task default: [:test]
