/*
 * cuda_cmds.h
  *
 * 
 *
 *
 */
#ifndef PGSTROM_CUDA_CMDS_H
#define PGSTROM_CUDA_CMDS_H

#define PGSTROM_GPU_NUM_VREGS	120

enum GpuCmds {
	GPUCMD_TERMINAL_COMMAND = 0,	/* End of command series */

	/*
	 * Const References
	 */
	GPUCMD_CONREF_NULL,
	GPUCMD_CONREF_BOOL,
	GPUCMD_CONREF_INT2,
	GPUCMD_CONREF_INT4,
	GPUCMD_CONREF_INT8,
	GPUCMD_CONREF_FLOAT4,
	GPUCMD_CONREF_FLOAT8,

	/*
	 * Variable References
	 */
	GPUCMD_VARREF_BOOL,
	GPUCMD_VARREF_INT2,
	GPUCMD_VARREF_INT4,
	GPUCMD_VARREF_INT8,
	GPUCMD_VARREF_FLOAT4,
	GPUCMD_VARREF_FLOAT8,

	/*
	 * Cast of data types
	 */
	GPUCMD_CAST_INT2_TO_INT4,
	GPUCMD_CAST_INT2_TO_INT8,
	GPUCMD_CAST_INT2_TO_FLOAT4,
	GPUCMD_CAST_INT2_TO_FLOAT8,
	GPUCMD_CAST_INT4_TO_INT2,
	GPUCMD_CAST_INT4_TO_INT8,
	GPUCMD_CAST_INT4_TO_FLOAT4,
	GPUCMD_CAST_INT4_TO_FLOAT8,
	GPUCMD_CAST_INT8_TO_INT2,
	GPUCMD_CAST_INT8_TO_INT4,
	GPUCMD_CAST_INT8_TO_FLOAT4,
	GPUCMD_CAST_INT8_TO_FLOAT8,
	GPUCMD_CAST_FLOAT4_TO_INT2,
	GPUCMD_CAST_FLOAT4_TO_INT4,
	GPUCMD_CAST_FLOAT4_TO_INT8,
	GPUCMD_CAST_FLOAT4_TO_FLOAT8,
	GPUCMD_CAST_FLOAT8_TO_INT2,
	GPUCMD_CAST_FLOAT8_TO_INT4,
	GPUCMD_CAST_FLOAT8_TO_INT8,
	GPUCMD_CAST_FLOAT8_TO_FLOAT4,

	/*
	 * Boolean operations
	 */
	GPUCMD_BOOLOP_AND,
	GPUCMD_BOOLOP_OR,
	GPUCMD_BOOLOP_NOT,

	/*
	 * Tentative for Testing
	 */
	GPUCMD_OPER_FLOAT8_LT,
	GPUCMD_OPER_FLOAT8_MI,
	GPUCMD_OPER_FLOAT8_PL,
	GPUCMD_FUNC_POWER,
	


	
	
	
	
};

#endif	/* PGSTROM_CUDA_CMDS_H */
