/*
 * cuda_cmds.h
  *
 * 
 *
 *
 */
#ifndef PGSTROM_CUDA_CMDS_H
#define PGSTROM_CUDA_CMDS_H

#define PGSTROM_GPU_NUM_VREGS	120

enum GpuCmds {
	GPUCMD_TERMINAL_COMMAND = 0,	/* End of command series */

	/*
	 * Const References
	 */
	GPUCMD_CONREF_NULL,
	GPUCMD_CONREF_BOOL,
	GPUCMD_CONREF_INT2,
	GPUCMD_CONREF_INT4,
	GPUCMD_CONREF_INT8,
	GPUCMD_CONREF_FLOAT4,
	GPUCMD_CONREF_FLOAT8,

	/*
	 * Variable References
	 */
	GPUCMD_VARREF_BOOL,
	GPUCMD_VARREF_INT2,
	GPUCMD_VARREF_INT4,
	GPUCMD_VARREF_INT8,
	GPUCMD_VARREF_FLOAT4,
	GPUCMD_VARREF_FLOAT8,

	/*
	 * Boolean operations
	 */
	GPUCMD_BOOLOP_AND,
	GPUCMD_BOOLOP_OR,
	GPUCMD_BOOLOP_NOT,

	/*
	 * Cast of data types
	 */
	GPUCMD_CAST_INT2_TO_INT4,
	GPUCMD_CAST_INT2_TO_INT8,
	GPUCMD_CAST_INT2_TO_FLOAT4,
	GPUCMD_CAST_INT2_TO_FLOAT8,
	GPUCMD_CAST_INT4_TO_INT2,
	GPUCMD_CAST_INT4_TO_INT8,
	GPUCMD_CAST_INT4_TO_FLOAT4,
	GPUCMD_CAST_INT4_TO_FLOAT8,
	GPUCMD_CAST_INT8_TO_INT2,
	GPUCMD_CAST_INT8_TO_INT4,
	GPUCMD_CAST_INT8_TO_FLOAT4,
	GPUCMD_CAST_INT8_TO_FLOAT8,
	GPUCMD_CAST_FLOAT4_TO_INT2,
	GPUCMD_CAST_FLOAT4_TO_INT4,
	GPUCMD_CAST_FLOAT4_TO_INT8,
	GPUCMD_CAST_FLOAT4_TO_FLOAT8,
	GPUCMD_CAST_FLOAT8_TO_INT2,
	GPUCMD_CAST_FLOAT8_TO_INT4,
	GPUCMD_CAST_FLOAT8_TO_INT8,
	GPUCMD_CAST_FLOAT8_TO_FLOAT4,

	/* '+' : add operators */
	GPUCMD_OPER_INT2_PL,
	GPUCMD_OPER_INT24_PL,
	GPUCMD_OPER_INT28_PL,
	GPUCMD_OPER_INT42_PL,
	GPUCMD_OPER_INT4_PL,
	GPUCMD_OPER_INT48_PL,
	GPUCMD_OPER_INT8_PL,
	GPUCMD_OPER_INT82_PL,
	GPUCMD_OPER_INT84_PL,
	GPUCMD_OPER_FLOAT4_PL,
	GPUCMD_OPER_FLOAT48_PL,
	GPUCMD_OPER_FLOAT84_PL,
	GPUCMD_OPER_FLOAT8_PL,

	/* '-' : subtract operators */
	GPUCMD_OPER_INT2_MI,
	GPUCMD_OPER_INT24_MI,
	GPUCMD_OPER_INT28_MI,
	GPUCMD_OPER_INT42_MI,
	GPUCMD_OPER_INT4_MI,
	GPUCMD_OPER_INT48_MI,
	GPUCMD_OPER_INT8_MI,
	GPUCMD_OPER_INT82_MI,
	GPUCMD_OPER_INT84_MI,
	GPUCMD_OPER_FLOAT4_MI,
	GPUCMD_OPER_FLOAT48_MI,
	GPUCMD_OPER_FLOAT84_MI,
	GPUCMD_OPER_FLOAT8_MI,

	/* '*' : mutiply operators */
	GPUCMD_OPER_INT2_MUL,
	GPUCMD_OPER_INT24_MUL,
	GPUCMD_OPER_INT28_MUL,
	GPUCMD_OPER_INT42_MUL,
	GPUCMD_OPER_INT4_MUL,
	GPUCMD_OPER_INT48_MUL,
	GPUCMD_OPER_INT8_MUL,
	GPUCMD_OPER_INT82_MUL,
	GPUCMD_OPER_INT84_MUL,
	GPUCMD_OPER_FLOAT4_MUL,
	GPUCMD_OPER_FLOAT48_MUL,
	GPUCMD_OPER_FLOAT84_MUL,
	GPUCMD_OPER_FLOAT8_MUL,

	/* '/' : divide operators */
	GPUCMD_OPER_INT2_DIV,
	GPUCMD_OPER_INT24_DIV,
	GPUCMD_OPER_INT28_DIV,
	GPUCMD_OPER_INT42_DIV,
	GPUCMD_OPER_INT4_DIV,
	GPUCMD_OPER_INT48_DIV,
	GPUCMD_OPER_INT8_DIV,
	GPUCMD_OPER_INT82_DIV,
	GPUCMD_OPER_INT84_DIV,
	GPUCMD_OPER_FLOAT4_DIV,
	GPUCMD_OPER_FLOAT48_DIV,
	GPUCMD_OPER_FLOAT84_DIV,
	GPUCMD_OPER_FLOAT8_DIV,

	/* '%' : reminder operators */
	GPUCMD_OPER_INT2_MOD,
	GPUCMD_OPER_INT4_MOD,
	GPUCMD_OPER_INT8_MOD,

	/* '+' : unary plus operators */
	GPUCMD_OPER_INT2_UP,
	GPUCMD_OPER_INT4_UP,
	GPUCMD_OPER_INT8_UP,
	GPUCMD_OPER_FLOAT4_UP,
	GPUCMD_OPER_FLOAT8_UP,

	/* '-' : unary minus operators */
	GPUCMD_OPER_INT2_UM,
	GPUCMD_OPER_INT4_UM,
	GPUCMD_OPER_INT8_UM,
	GPUCMD_OPER_FLOAT4_UM,
	GPUCMD_OPER_FLOAT8_UM,

	/* '@' : absolute value operators */
	GPUCMD_OPER_INT2_ABS,
	GPUCMD_OPER_INT4_ABS,
	GPUCMD_OPER_INT8_ABS,
	GPUCMD_OPER_FLOAT4_ABS,
	GPUCMD_OPER_FLOAT8_ABS,

	/* '=' : equal operators */
	GPUCMD_OPER_INT2_EQ,
	GPUCMD_OPER_INT24_EQ,
	GPUCMD_OPER_INT28_EQ,
	GPUCMD_OPER_INT42_EQ,
	GPUCMD_OPER_INT4_EQ,
	GPUCMD_OPER_INT48_EQ,
	GPUCMD_OPER_INT82_EQ,
	GPUCMD_OPER_INT84_EQ,
	GPUCMD_OPER_INT8_EQ,
	GPUCMD_OPER_FLOAT4_EQ,
	GPUCMD_OPER_FLOAT48_EQ,
	GPUCMD_OPER_FLOAT84_EQ,
	GPUCMD_OPER_FLOAT8_EQ,

	/* '<>' : not equal operators */
	GPUCMD_OPER_INT2_NE,
	GPUCMD_OPER_INT24_NE,
	GPUCMD_OPER_INT28_NE,
	GPUCMD_OPER_INT42_NE,
	GPUCMD_OPER_INT4_NE,
	GPUCMD_OPER_INT48_NE,
	GPUCMD_OPER_INT82_NE,
	GPUCMD_OPER_INT84_NE,
	GPUCMD_OPER_INT8_NE,
	GPUCMD_OPER_FLOAT4_NE,
	GPUCMD_OPER_FLOAT48_NE,
	GPUCMD_OPER_FLOAT84_NE,
	GPUCMD_OPER_FLOAT8_NE,

	/* '>' : equal operators */
	GPUCMD_OPER_INT2_GT,
	GPUCMD_OPER_INT24_GT,
	GPUCMD_OPER_INT28_GT,
	GPUCMD_OPER_INT42_GT,
	GPUCMD_OPER_INT4_GT,
	GPUCMD_OPER_INT48_GT,
	GPUCMD_OPER_INT82_GT,
	GPUCMD_OPER_INT84_GT,
	GPUCMD_OPER_INT8_GT,
	GPUCMD_OPER_FLOAT4_GT,
	GPUCMD_OPER_FLOAT48_GT,
	GPUCMD_OPER_FLOAT84_GT,
	GPUCMD_OPER_FLOAT8_GT,

	/* '<' : equal operators */
	GPUCMD_OPER_INT2_LT,
	GPUCMD_OPER_INT24_LT,
	GPUCMD_OPER_INT28_LT,
	GPUCMD_OPER_INT42_LT,
	GPUCMD_OPER_INT4_LT,
	GPUCMD_OPER_INT48_LT,
	GPUCMD_OPER_INT82_LT,
	GPUCMD_OPER_INT84_LT,
	GPUCMD_OPER_INT8_LT,
	GPUCMD_OPER_FLOAT4_LT,
	GPUCMD_OPER_FLOAT48_LT,
	GPUCMD_OPER_FLOAT84_LT,
	GPUCMD_OPER_FLOAT8_LT,

	/* '>=' : relational greater-than or equal-to */
	GPUCMD_OPER_INT2_GE,
	GPUCMD_OPER_INT24_GE,
	GPUCMD_OPER_INT28_GE,
	GPUCMD_OPER_INT42_GE,
	GPUCMD_OPER_INT4_GE,
	GPUCMD_OPER_INT48_GE,
	GPUCMD_OPER_INT82_GE,
	GPUCMD_OPER_INT84_GE,
	GPUCMD_OPER_INT8_GE,
	GPUCMD_OPER_FLOAT4_GE,
	GPUCMD_OPER_FLOAT48_GE,
	GPUCMD_OPER_FLOAT84_GE,
	GPUCMD_OPER_FLOAT8_GE,

	/* '<=' : relational greater-than or equal-to */
	GPUCMD_OPER_INT2_LE,
	GPUCMD_OPER_INT24_LE,
	GPUCMD_OPER_INT28_LE,
	GPUCMD_OPER_INT42_LE,
	GPUCMD_OPER_INT4_LE,
	GPUCMD_OPER_INT48_LE,
	GPUCMD_OPER_INT82_LE,
	GPUCMD_OPER_INT84_LE,
	GPUCMD_OPER_INT8_LE,
	GPUCMD_OPER_FLOAT4_LE,
	GPUCMD_OPER_FLOAT48_LE,
	GPUCMD_OPER_FLOAT84_LE,
	GPUCMD_OPER_FLOAT8_LE,

	/* '&' : bitwise and */
	GPUCMD_OPER_INT2_AND,
	GPUCMD_OPER_INT4_AND,
	GPUCMD_OPER_INT8_AND,

	/* '|'  : bitwise or */
	GPUCMD_OPER_INT2_OR,
	GPUCMD_OPER_INT4_OR,
	GPUCMD_OPER_INT8_OR,

	/* '#'  : bitwise xor */
	GPUCMD_OPER_INT2_XOR,
	GPUCMD_OPER_INT4_XOR,
	GPUCMD_OPER_INT8_XOR,

	/* '~'  : bitwise not operators */
	GPUCMD_OPER_INT2_NOT,
	GPUCMD_OPER_INT4_NOT,
	GPUCMD_OPER_INT8_NOT,

	/* '>>' : right shift */
	GPUCMD_OPER_INT2_SHR,
	GPUCMD_OPER_INT4_SHR,
	GPUCMD_OPER_INT8_SHR,

	/* '<<' : left shift */
	GPUCMD_OPER_INT2_SHL,
	GPUCMD_OPER_INT4_SHL,
	GPUCMD_OPER_INT8_SHL,

	/*
	 * Mathmatical functions
	 */
	GPUCMD_FUNC_FLOAT8_CBRT,
	GPUCMD_FUNC_FLOAT8_CEIL,
	GPUCMD_FUNC_FLOAT8_EXP,
	GPUCMD_FUNC_FLOAT8_FLOOR,
	GPUCMD_FUNC_FLOAT8_LOG,
	GPUCMD_FUNC_FLOAT8_LOG10,
	GPUCMD_FUNC_FLOAT8_PI,
	GPUCMD_FUNC_FLOAT8_POWER,
	GPUCMD_FUNC_FLOAT8_ROUND,
	GPUCMD_FUNC_FLOAT8_SIGN,
	GPUCMD_FUNC_FLOAT8_SQRT,
	GPUCMD_FUNC_FLOAT8_TRUNC,

	/*
     * Trigonometric function
     */
	GPUCMD_FUNC_FLOAT8_ACOS,
	GPUCMD_FUNC_FLOAT8_ASIN,
	GPUCMD_FUNC_FLOAT8_ATAN,
	GPUCMD_FUNC_FLOAT8_ATAN2,
	GPUCMD_FUNC_FLOAT8_COS,
	GPUCMD_FUNC_FLOAT8_COT,
	GPUCMD_FUNC_FLOAT8_SIN,
	GPUCMD_FUNC_FLOAT8_TAN,
};

#endif	/* PGSTROM_CUDA_CMDS_H */
