PG_CONFIG ?= pg_config
VERSION ?= 6.2
RELEASE ?= 0
GITHASH_IF_NOT_GIVEN := HEAD

#
# PostgreSQL major version
#
PG_INCLUDEDIR_SERVER := $(shell $(PG_CONFIG) --includedir-server)
__PG_CONFIG_H   := $(PG_INCLUDEDIR_SERVER)/pg_config.h
PG_MAJORVERSION := $(shell grep '^#define PG_MAJORVERSION_NUM' $(__PG_CONFIG_H) | awk '{print $$3}')
PG_MINORVERSION := $(shell grep '^#define PG_MINORVERSION_NUM' $(__PG_CONFIG_H) | awk '{print $$3}')
PG_VERSION_NUM  := $(shell grep '^#define PG_VERSION_NUM'      $(__PG_CONFIG_H) | awk '{print $$3}')

#
# PG-Strom version signature
#
ifeq ($(shell echo $(RELEASE) | grep -E '^[0-9]+'),)
PGSTROM_VERSION := $(VERSION)$(RELEASE)
else
PGSTROM_VERSION := $(VERSION).$(RELEASE)
endif

#
# GitHash to build
#
ifeq ($(GITHASH),)
GITHASH := $(shell git rev-parse HEAD 2>/dev/null)
ifeq ($(GITHASH),)
GITHASH := $(GITHASH_IF_NOT_GIVEN)
else
ifeq ($(shell git diff | wc -l),0)
PGSTROM_GITHASH := $(GITHASH)
else
PGSTROM_GITHASH := $(GITHASH)::local_changes
endif
endif
endif

#
# Shell commands
#
CXX       ?= g++
PG_CONFIG ?= pg_config
PKGCONF   ?= $(shell which pkgconf 2>/dev/null || which pkg-config 2>/dev/null)

#
# features which will be dropped at v6.3 timeline
#
WITH_POSTGIS ?= 0
