--#
--#       Gpu PreAggregate Explain TestCases
--#

-- global configuration
set pg_strom.gpu_setup_cost to 0;
set pg_strom.debug_force_gpupreagg to on;
set pg_strom.enable_gpusort to off;
set client_min_messages to warning;

-- explain normal case
set pg_strom.enabled=off;
explain (verbose, costs off, timing off) select key,avg(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(smlint_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(smlint_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(smlint_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(smlint_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(smlint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(smlint_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(smlint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(integer_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(integer_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(integer_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(integer_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(integer_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(integer_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(integer_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(bigint_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(bigint_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(bigint_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(bigint_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(bigint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(bigint_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(bigint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(real_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(real_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(real_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(real_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(real_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(real_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(real_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(float_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(float_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(float_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(float_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(float_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(float_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(float_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(nume_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(nume_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(nume_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(nume_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(nume_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(nume_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(nume_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(smlsrl_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(smlsrl_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(smlsrl_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(smlsrl_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(smlsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(smlsrl_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(smlsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(serial_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(serial_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(serial_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(serial_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(serial_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(serial_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(serial_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(bigsrl_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(bigsrl_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(bigsrl_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(bigsrl_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(bigsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(bigsrl_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(bigsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_x,bigsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_x,bigsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_x,bigsrl_x) from strom_test group by key order by key;

set pg_strom.enabled=on;
explain (verbose, costs off, timing off) select key,avg(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(smlint_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(smlint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(smlint_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(smlint_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(smlint_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(smlint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(smlint_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(smlint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_x,smlint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(integer_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(integer_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(integer_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(integer_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(integer_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(integer_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(integer_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(integer_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_x,integer_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(bigint_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(bigint_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(bigint_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(bigint_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(bigint_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(bigint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(bigint_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(bigint_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_x,bigint_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(real_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(real_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(real_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(real_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(real_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(real_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(real_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(real_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_x,real_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(float_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(float_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(float_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(float_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(float_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(float_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(float_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(float_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_x,float_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(nume_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(nume_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(nume_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(nume_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(nume_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(nume_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(nume_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(nume_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_x,nume_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(smlsrl_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(smlsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(smlsrl_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(smlsrl_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(smlsrl_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(smlsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(smlsrl_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(smlsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_x,smlsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(serial_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(serial_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(serial_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(serial_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(serial_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(serial_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(serial_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(serial_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_x,serial_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,avg(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,count(bigsrl_x)          from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,max(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,min(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,sum(bigsrl_x)            from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev(bigsrl_x)         from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_pop(bigsrl_x)     from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,stddev_samp(bigsrl_x)    from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,variance(bigsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_pop(bigsrl_x)        from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,var_samp(bigsrl_x)       from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_x,bigsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_x,bigsrl_x) from strom_test group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_x,bigsrl_x) from strom_test group by key order by key;

--explain aggregate function for statistic query case.
set pg_strom.enabled=off;
explain (verbose, costs off, timing off) select key,corr(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;

set pg_strom.enabled=on;
explain (verbose, costs off, timing off) select key,corr(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_x,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlint_y,smlint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_x,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(integer_y,integer_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_x,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigint_y,bigint_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_x,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(real_y,real_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_x,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(float_y,float_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_x,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(nume_y,nume_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_x,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(smlsrl_y,smlsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_x,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(serial_y,serial_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,corr(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_pop(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_x,bigsrl_z) from strom_mix group by key order by key;
explain (verbose, costs off, timing off) select key,covar_samp(bigsrl_y,bigsrl_z) from strom_mix group by key order by key;set client_min_messages to warning;


-- explain zero query case.
set pg_strom.enabled=off;
explain (verbose, costs off, timing off) select avg(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(smlint_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(smlint_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(smlint_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(smlint_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(smlint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(smlint_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(smlint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(integer_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(integer_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(integer_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(integer_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(integer_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(integer_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(integer_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(bigint_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(bigint_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(bigint_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(bigint_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(bigint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(bigint_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(bigint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(real_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(real_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(real_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(real_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(real_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(real_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(real_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(float_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(float_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(float_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(float_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(float_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(float_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(float_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(nume_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(nume_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(nume_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(nume_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(nume_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(nume_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(nume_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(smlsrl_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(smlsrl_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(smlsrl_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(smlsrl_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(smlsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(smlsrl_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(smlsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(serial_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(serial_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(serial_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(serial_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(serial_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(serial_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(serial_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(bigsrl_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(bigsrl_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(bigsrl_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(bigsrl_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(bigsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(bigsrl_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(bigsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(bigsrl_x,bigsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(bigsrl_x,bigsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(bigsrl_x,bigsrl_x) from strom_zero_test ;

set pg_strom.enabled=on;
explain (verbose, costs off, timing off) select avg(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(smlint_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(smlint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(smlint_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(smlint_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(smlint_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(smlint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(smlint_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(smlint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(smlint_x,smlint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(integer_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(integer_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(integer_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(integer_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(integer_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(integer_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(integer_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(integer_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(integer_x,integer_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(bigint_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(bigint_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(bigint_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(bigint_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(bigint_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(bigint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(bigint_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(bigint_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(bigint_x,bigint_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(real_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(real_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(real_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(real_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(real_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(real_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(real_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(real_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(real_x,real_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(float_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(float_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(float_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(float_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(float_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(float_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(float_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(float_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(float_x,float_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(nume_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(nume_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(nume_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(nume_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(nume_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(nume_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(nume_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(nume_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(nume_x,nume_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(smlsrl_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(smlsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(smlsrl_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(smlsrl_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(smlsrl_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(smlsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(smlsrl_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(smlsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(smlsrl_x,smlsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(serial_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(serial_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(serial_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(serial_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(serial_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(serial_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(serial_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(serial_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(serial_x,serial_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select avg(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select count(bigsrl_x)          from strom_zero_test ;
explain (verbose, costs off, timing off) select max(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select min(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select sum(bigsrl_x)            from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev(bigsrl_x)         from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_pop(bigsrl_x)     from strom_zero_test ;
explain (verbose, costs off, timing off) select stddev_samp(bigsrl_x)    from strom_zero_test ;
explain (verbose, costs off, timing off) select variance(bigsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select var_pop(bigsrl_x)        from strom_zero_test ;
explain (verbose, costs off, timing off) select var_samp(bigsrl_x)       from strom_zero_test ;
explain (verbose, costs off, timing off) select corr(bigsrl_x,bigsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_pop(bigsrl_x,bigsrl_x) from strom_zero_test ;
explain (verbose, costs off, timing off) select covar_samp(bigsrl_x,bigsrl_x) from strom_zero_test ;


-- division by zero with GpuPreAggregate
set pg_strom.enabled=off;
explain (verbose on, costs off) select sum(smlint_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(integer_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(bigint_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(real_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(float_x/(id%1000)) from strom_test;

set pg_strom.enabled=on;
explain (verbose on, costs off) select sum(smlint_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(integer_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(bigint_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(real_x/(id%1000)) from strom_test;
explain (verbose on, costs off) select sum(float_x/(id%1000)) from strom_test;


--explain GpuPreAggregation for Data/Time types
set pg_strom.enabled=off;
explain (verbose on, costs off) select key,max(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,avg(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,avg(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select max(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select max(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select max(date_x) from strom_time_test;
explain (verbose on, costs off) select max(time_x) from strom_time_test;
explain (verbose on, costs off) select max(timetz_x) from strom_time_test;
explain (verbose on, costs off) select max(interval_x) from strom_time_test;
explain (verbose on, costs off) select min(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select min(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select min(date_x) from strom_time_test;
explain (verbose on, costs off) select min(time_x) from strom_time_test;
explain (verbose on, costs off) select min(timetz_x) from strom_time_test;
explain (verbose on, costs off) select min(interval_x) from strom_time_test;
explain (verbose on, costs off) select count(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select count(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select count(date_x) from strom_time_test;
explain (verbose on, costs off) select count(time_x) from strom_time_test;
explain (verbose on, costs off) select count(timetz_x) from strom_time_test;
explain (verbose on, costs off) select count(interval_x) from strom_time_test;
explain (verbose on, costs off) select avg(time_x) from strom_time_test;
explain (verbose on, costs off) select avg(interval_x) from strom_time_test;

set pg_strom.enabled=on;
explain (verbose on, costs off) select key,max(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,max(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,min(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timestamp_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timestamptz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(date_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(timetz_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,count(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,avg(time_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select key,avg(interval_x) from strom_time_test group by key order by key;
explain (verbose on, costs off) select max(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select max(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select max(date_x) from strom_time_test;
explain (verbose on, costs off) select max(time_x) from strom_time_test;
explain (verbose on, costs off) select max(timetz_x) from strom_time_test;
explain (verbose on, costs off) select max(interval_x) from strom_time_test;
explain (verbose on, costs off) select min(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select min(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select min(date_x) from strom_time_test;
explain (verbose on, costs off) select min(time_x) from strom_time_test;
explain (verbose on, costs off) select min(timetz_x) from strom_time_test;
explain (verbose on, costs off) select min(interval_x) from strom_time_test;
explain (verbose on, costs off) select count(timestamp_x) from strom_time_test;
explain (verbose on, costs off) select count(timestamptz_x) from strom_time_test;
explain (verbose on, costs off) select count(date_x) from strom_time_test;
explain (verbose on, costs off) select count(time_x) from strom_time_test;
explain (verbose on, costs off) select count(timetz_x) from strom_time_test;
explain (verbose on, costs off) select count(interval_x) from strom_time_test;
explain (verbose on, costs off) select avg(time_x) from strom_time_test;
explain (verbose on, costs off) select avg(interval_x) from strom_time_test;
